# Generated by Django 6.0.1 on 2026-04-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contact',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
