# Generated by Django 6.0.1 on 2026-04-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_item_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='contact',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
