# Generated by Django 4.2.30 on 2026-07-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_item_created_at_item_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, default='Other', max_length=50, null=True),
        ),
    ]
