# Generated by Django 4.2.30 on 2026-07-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_item_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
